---
title: "Predictors"
output: html_document
date: "2024-03-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load libraries
library(readr) # for reading in data
library(tidyr)
library(dplyr) # for data cleaning
library(purrr) # for functional programming
library(forcats) # for recoding factors
library(limSolve) # for solving linear equations
library(sqldf)
library(XML)
library(RCurl)
library(elo)
setwd("/Users/jakesak/Documents/MM Mania Kaggle/Code")

CompactResults <- read.csv(file.path("../Data", "MRegularSeasonCompactResults.csv" ))
DetailedResults <- read.csv(file.path("../Data", "MRegularSeasonDetailedResults.csv" ))
CompactResults <- CompactResults %>% filter(Season >= min(DetailedResults$Season))
```



```{r}
#Mens ELO Code
test <- function(params) {
  K = params[1]
  loc = params[2]
  score = params[3]
  date = params[4]
  for (year in min(CompactResults$Season):max(CompactResults$Season)) {
    results <- CompactResults[which(CompactResults$Season == year),]
    #Remove rows with NA, NaN, or Inf in critical columns
    results <- results[!is.na(results$WScore) & !is.na(results$LScore) 
                       & is.finite(results$WScore) & is.finite(results$LScore), ]
    results <- results[is.finite(results$DayNum),]
    #Add result col for scoring elo, 1 for win, 0.5 for ot win
    results$result <- ifelse(results$NumOT > 0, 0.5, 1)
    #results$result <- score(results$WScore, results$LScore)
    
    #Add score margin, half margin if overtime
    results$Margin <- ifelse(results$NumOT >0, 0.5*(results$WScore - results$LScore),
                             results$WScore - results$LScore)
    #Cap off margin to exclude blowouts
    margin_cap = 25
    results$Margin <- pmin(results$Margin, margin_cap)
    
    #Add Location value, 1 for home win, -1 for away win, 0 for neutral
    results$Loc <- ifelse(results$WLoc == "H", -1, 
                          ifelse(results$WLoc == "A", 1, 0)) * loc
    
    #Reverse Day Num so regressed for earlier games
    results$ReverseDayNum <- (max(results$DayNum) + 1) - results$DayNum 
    
    
    #Confirm data is clean
    results <- results[is.finite(results$Loc) & is.finite(results$DayNum),]
    
    #Create the elo model
    elo_model <- elo.run(data = results, 
                         formula = result ~ 
                           adjust(as.character(WTeamID), Loc)
                         + as.character(LTeamID) + 
                           regress(ReverseDayNum, 1500, date), 
                         k = (K + (results$Margin*score)) )
    
    #Expand elo model to data frame
    elo_results <- elo_model %>%
      as.data.frame()
    #Combine results data with elo data
    results2 <- cbind(results, elo_results)
    
    
    #Test on 2nd half of season
    mid_date <- median(results$DayNum)
    test_model <- results[
      which(results$DayNum > mid_date),]
    results3 <- merge(x = results2, y = test_model[c("Season", "DayNum",
                                                         "WTeamID","LTeamID")], 
                      by = c("Season", "DayNum","WTeamID", "LTeamID"), all.y = TRUE)
    
    #Final elos function, add year and team id
    final_elos <- as.data.frame(final.elos(elo_model))
    names(final_elos)[1] <- "ELO"
    final_elos$Season <- year
    final_elos$TeamID <- row.names(final_elos)
    final_elos$TeamID <- as.integer(row.names(final_elos))

    
    #If first year, create final elo dataframe otherwise add final elo for every year
    ifelse(year == min(CompactResults$Season), final_elo <- final_elos, 
           final_elo <- rbind(final_elo, final_elos))
    #If first year, create all games dataframe, otherwise add results2 for every year
    ifelse(year == min(CompactResults$Season), all_games <- results2, 
           all_games <- rbind(all_games, results2))
  }
  final_elo <<- final_elo
  all_games <<- na.omit(all_games)
  results3$error <- (results3$result - results3$p.A)^2
  errorVal <- sum(results3$error)/nrow(results3)
  
  #Confirm data is finite
  if (!is.finite(errorVal)) {
    warning("Non-finite value encountered. Returning a large number instead.")
    return(1e6)  # Return a large but finite value to indicate a poor fit
  }
  return(errorVal)
}

optim(par=c(0,0,0,0), fn=test, 
      lower = c(0,-Inf,-Inf,0), upper = c(Inf,Inf,Inf,1), method="L-BFGS-B")
FinalElo_M <- final_elo
```



```{r}
FinalElo_M <- read.csv(file.path("../Data", "final_elo_M.csv" ))
ELO <- FinalElo_M

suppressMessages(
for (year in min(CompactResults$Season):max(CompactResults$Season)) {
  data <- CompactResults[which(CompactResults$Season == year),]
  elo_season <- ELO[which(ELO$Season == year),]
  #Data when winning
  wins_df <- data %>% 
    group_by(WTeamID, Season) %>% 
    summarize(WPts_for = sum(WScore), WPts_against = sum(LScore), 
              WPts_diff = mean(WScore - LScore), Wins = n()) %>%
    rename(TeamID = WTeamID)
  #Data when losing
  loss_df <- data %>% 
    group_by(LTeamID, Season) %>% 
    summarize(LPts_for = sum(LScore), LPts_against = sum(WScore), 
              LPts_diff = mean(LScore - WScore), Losses = n(),
              LBlowouts = sum((WScore-LScore) >= 25 ),
              LClose = sum((WScore-LScore) <= 5 )) %>% 
    rename(TeamID = LTeamID)
  #Merge and clean
  results <- merge(wins_df, loss_df, by = c("TeamID", "Season"), all = TRUE)
  results$Wins[is.na(results$Wins)] <- 0
  results$Losses[is.na(results$Losses)] <- 0
  #Create winning percentage, points for, and points against cols
  results <- results %>% 
    group_by(TeamID, Season) %>% 
    mutate(Games = Wins+Losses, 
           Win_pct = Wins/(Wins+Losses), 
           Pts_for = (WPts_for+LPts_for)/(Wins+Losses), 
           Pts_against = (WPts_against+LPts_against)/(Wins+Losses),
           Pts_diff = (WPts_diff*Wins+LPts_diff*Losses)/(Wins+Losses)) %>% 
    select(Season, TeamID, Games, Win_pct, Pts_for, Pts_against, Pts_diff, LBlowouts, LClose)
  #Raw SOS (based on opponent winning percentage)
  raw_sosW <- data %>%
    left_join(results, by  = c("LTeamID" = "TeamID", "Season")) %>%
    group_by(WTeamID, Season) %>% 
    summarize(WSOS = mean(Win_pct), WNum = n()) %>% 
    rename(TeamID = WTeamID)
  raw_sosL <- data %>%
    left_join(results, by  = c("WTeamID" = "TeamID", "Season")) %>%
    group_by(LTeamID, Season) %>% 
    summarize(LSOS = mean(Win_pct), LNum = n()) %>% 
    rename(TeamID = LTeamID)
  raw_sos <- merge(raw_sosW, raw_sosL, by = c("TeamID", "Season"), all = TRUE)
  raw_sos$WSOS[is.na(raw_sos$WSOS)] <- 0
  raw_sos$LSOS[is.na(raw_sos$LSOS)] <- 0
  raw_sos$WNum[is.na(raw_sos$WNum)] <- 0
  raw_sos$LNum[is.na(raw_sos$LNum)] <- 0
  raw_sos <- raw_sos %>% 
    mutate(rawSOS = ((WSOS*WNum)+(LSOS*LNum))/(WNum+LNum))
  #ELO SOS (based on opponent elo from prior calculations)
  elo_sosW <- data %>%
    left_join(elo_season, by  = c("LTeamID" = "TeamID", "Season")) %>%
    group_by(WTeamID, Season) %>% 
    summarize(WELOSOS = mean(ELO), WNum = n()) %>% 
    rename(TeamID = WTeamID)
  elo_sosL <- data %>%
    left_join(elo_season, by  = c("WTeamID" = "TeamID", "Season")) %>%
    group_by(LTeamID, Season) %>% 
    summarize(LELOSOS = mean(ELO), LNum = n()) %>% 
    rename(TeamID = LTeamID)
  elo_sos <- merge(elo_sosW, elo_sosL, by = c("TeamID", "Season"), all = TRUE)
  elo_sos$WELOSOS[is.na(elo_sos$WELOSOS)] <- 0
  elo_sos$LELOSOS[is.na(elo_sos$LELOSOS)] <- 0
  elo_sos$WNum[is.na(elo_sos$WNum)] <- 0
  elo_sos$LNum[is.na(elo_sos$LNum)] <- 0
  elo_sos <- elo_sos %>% 
    mutate(ELOSOS = ((WELOSOS*WNum)+(LELOSOS*LNum))/(WNum+LNum))
  #All SOS data
  SOS <- merge(elo_sos, raw_sos, by = c("TeamID", "Season"), all = TRUE) %>%
    select(Season, TeamID, rawSOS, ELOSOS)
  
   #Wins vs top 50 teams
  WOppElo <- data %>% 
    left_join(ELO, by = c("LTeamID" = "TeamID", "Season")) %>%
    group_by(WTeamID, Season) %>% 
    rename(LRank = Rank) %>% 
    filter(LRank <= 50) %>% 
    summarize(Quad1W = n()) %>% 
    rename(TeamID = WTeamID)
  #Loss vs top 50 teams
  LOppElo <- data %>% 
    left_join(ELO, by = c("WTeamID" = "TeamID", "Season")) %>%
    group_by(LTeamID, Season) %>% 
    rename(WRank = Rank) %>% 
    filter(WRank <= 50) %>% 
    summarize(Quad1L = n())%>% 
    rename(TeamID = LTeamID)
  #Record vs top 50 teams
  OppElo <- merge(WOppElo, LOppElo, by = c("TeamID", "Season"), all = TRUE) %>%
    mutate(Quad1Rec = Quad1W/(Quad1W + Quad1L), Quad1Games = (Quad1W + Quad1L)) %>%
    mutate(Quad1Rec = replace_na(Quad1Rec, 0), Quad1Games = replace_na(Quad1Games, 0)) %>% 
    select(Season, TeamID, Quad1Rec, Quad1Games)
  
  #Merge with SOS
  SOS_Q1 <- SOS %>% left_join(OppElo, by = c("Season", "TeamID"))
  #All simple team metrics
  results <- results %>% 
    left_join(SOS_Q1, by = c("Season", "TeamID"))
  #If first year, create final table, otherwise add data
  ifelse(year == min(CompactResults$Season), SimpleMetrics <- results, 
         SimpleMetrics <- rbind(SimpleMetrics, results))
})
SimpleMetrics_M <- SimpleMetrics
```



```{r}
#Mens Detailed Metrics
suppressMessages(
for (year in min(DetailedResults$Season):max(DetailedResults$Season)) {
  data <- DetailedResults[which(DetailedResults$Season == year),]
  #fg pct, 3pt pct, #3pt att/total att, ft att
  #In wins
  Wfg_df <- data %>% 
    group_by(WTeamID, Season) %>% 
    summarize(WFgPct = (sum(WFGM))/(sum(WFGA)), 
              W3PtPct = (sum(WFGM3))/(sum(WFGA3)), 
              W3PtShots = (sum(WFGA3))/(sum(WFGA)), 
              WFtPct = (sum(WFTM))/(sum(WFTA)),
              WFtA = (sum(WFTA)/n()),
              Wins = n()) %>%
    rename(TeamID = WTeamID)
  #In losses 
  Lfg_df <- data %>% 
    group_by(LTeamID, Season) %>% 
    summarize(LFgPct = (sum(LFGM))/(sum(LFGA)), 
              L3PtPct = (sum(LFGM3))/(sum(LFGA3)), 
              L3PtShots = (sum(LFGA3))/(sum(LFGA)), 
              LFtPct = (sum(LFTM))/(sum(LFTA)),
              LFtA = (sum(LFTA)/n()),
              Losses = n()) %>%
    rename(TeamID = LTeamID)
  #Merge and summarize
  fg_df <- merge(Wfg_df, Lfg_df, by = c("TeamID", "Season"), all = TRUE)
  fg_df$Wins[is.na(fg_df$Wins)] <- 0
  fg_df$Losses[is.na(fg_df$Losses)] <- 0
  fg_df <- fg_df %>% 
    group_by(TeamID, Season) %>%
    mutate(FgPct = (WFgPct*Wins+LFgPct*Losses)/(Wins+Losses), 
           ThreePtPct = (W3PtPct*Wins+L3PtPct*Losses)/(Wins+Losses),
           ThreePtShots = (W3PtShots*Wins+L3PtShots*Losses)/(Wins+Losses),
           FtPct = (WFtPct*Wins+LFtPct*Losses)/(Wins+Losses),
           FtA = (WFtA*Wins+LFtA*Losses)/(Wins+Losses),
           Games = (Wins + Losses))
  #opp in wins
  OppWfg_df <- data %>% 
    group_by(WTeamID, Season) %>% 
    summarize(OppWFgPct = (sum(LFGM))/(sum(LFGA)), 
              OppW3PtPct = (sum(LFGM3))/(sum(LFGA3)), 
              OppW3PtShots = (sum(LFGA3))/(sum(LFGA)),
              OppWFtA = (sum(LFTA)/n()),
              Wins = n()) %>%
    rename(TeamID = WTeamID)
  #opp in losses
  OppLfg_df <- data %>% 
    group_by(LTeamID, Season) %>% 
    summarize(OppLFgPct = (sum(WFGM))/(sum(WFGA)), 
              OppL3PtPct = (sum(WFGM3))/(sum(WFGA3)), 
              OppL3PtShots = (sum(WFGA3))/(sum(WFGA)), 
              OppLFtA = (sum(WFTA)/n()),
              Losses = n()) %>%
    rename(TeamID = LTeamID)
  #Merge and summarize
  opp_fg_df <- merge(OppWfg_df, OppLfg_df, by = c("TeamID", "Season"), all = TRUE)
  opp_fg_df$Wins[is.na(opp_fg_df$Wins)] <- 0
  opp_fg_df$Losses[is.na(opp_fg_df$Losses)] <- 0
  opp_fg_df <- opp_fg_df %>% 
    group_by(TeamID, Season) %>%
    mutate(OppFgPct = (OppWFgPct*Wins+OppLFgPct*Losses)/(Wins+Losses), 
           OppThreePtPct = (OppW3PtPct*Wins+OppL3PtPct*Losses)/(Wins+Losses),
           OppThreePtShots = (OppW3PtShots*Wins+OppL3PtShots*Losses)/(Wins+Losses),
           OppFtA = (OppWFtA*Wins+OppLFtA*Losses)/(Wins+Losses)) %>%
    select(-Wins, -Losses)
  fg_results <-  merge(fg_df, opp_fg_df, by = c("TeamID", "Season"), all = TRUE) %>% 
    select(Season, TeamID, FgPct, ThreePtPct, ThreePtShots, FtPct, FtA,
           OppFgPct, OppThreePtPct, OppThreePtShots, OppFtA, Wins, Losses, Games)
  #reb, oreb/opponent reb, blocks + steals, turnovers, asst/to
  #Win stats
  Wdef_df <- data %>% 
    group_by(WTeamID, Season) %>% 
    summarize(WReb = (sum(WOR + WDR)/n()), 
              WOReb = sum(WOR)/n(),
              WORebRat = (sum(WOR/LDR)/n()),
              WBlkStl = (sum(WBlk+WStl)/n()), 
              WTurn = (sum(WTO)/n()), 
              WTurnRat = (sum(WTO/LTO)/n()),
              WAsstRat = (sum(WAst/WTO)/n()),
              Wins = n()) %>%
    rename(TeamID = WTeamID)
  #Loss stats
  Ldef_df <- data %>% 
    group_by(LTeamID, Season) %>% 
    summarize(LReb = (sum(LOR + LDR)/n()), 
              LOReb = sum(LOR)/n(),
              LORebRat = (sum(LOR/(LOR +WDR))/n()),
              LBlkStl = (sum(LBlk+LStl)/n()), 
              LTurn = (sum(LTO)/n()), 
              LTurnRat = (sum(LTO/WTO)/n()),
              LAsstRat = (sum(LAst/LTO)/n()),
              Losses = n()) %>%
    rename(TeamID = LTeamID)
  #Merge and summarize
  def_df <- merge(Wdef_df, Ldef_df, by = c("TeamID", "Season"), all = TRUE)
  def_df$Wins[is.na(def_df$Wins)] <- 0
  def_df$Losses[is.na(def_df$Losses)] <- 0
  def_df <- def_df %>% 
    group_by(TeamID, Season) %>%
    mutate(Reb = (WReb*Wins+LReb*Losses)/(Wins+Losses),
           OReb = (WOReb*Wins+LOReb*Losses)/(Wins+Losses),
           ORebRat = (WORebRat*Wins+LORebRat*Losses)/(Wins+Losses),
           BlkStl = (WBlkStl*Wins+ LBlkStl*Losses)/(Wins+Losses),
           TO = (WTurn*Wins+ LTurn*Losses)/(Wins+Losses),
           TurnRat = (WTurnRat*Wins+ LTurnRat*Losses)/(Wins+Losses),
           AsstRat = (WAsstRat*Wins+ LAsstRat*Losses)/(Wins+Losses),
           Games = (Wins + Losses))
  #opp in wins 
  OppWdef_df <- data %>% 
    group_by(WTeamID, Season) %>% 
    summarize(OppWReb = (sum(LOR + LDR)/n()), 
              OppWORebRat = (sum(LOR/WDR)/n()),
              OppWBlkStl = (sum(LBlk+LStl)/n()), 
              OppWAsstRat = (sum(LAst/LTO)/n()),
              Wins = n()) %>%
    rename(TeamID = WTeamID)
  #opp in losses
  OppLdef_df <- data %>% 
    group_by(LTeamID, Season) %>% 
    summarize(OppLReb = (sum(WOR + WDR)/n()), 
              OppLORebRat = (sum(WOR/LDR)/n()),
              OppLBlkStl = (sum(WBlk+WStl)/n()), 
              OppLAsstRat = (sum(WAst/WTO)/n()),
              Losses = n()) %>%
    rename(TeamID = LTeamID)
  #Merge and summarize
  opp_def_df <- merge(OppWdef_df, OppLdef_df, by = c("TeamID", "Season"), all = TRUE)
  opp_def_df$Wins[is.na(opp_def_df$Wins)] <- 0
  opp_def_df$Losses[is.na(opp_def_df$Losses)] <- 0
  opp_def_df <- opp_def_df %>% 
    group_by(TeamID, Season) %>%
    mutate(OppReb = (OppWReb*Wins+OppLReb*Losses)/(Wins+Losses),
           OppORebRat = (OppWORebRat*Wins+OppLORebRat*Losses)/(Wins+Losses),
           OppBlkStl = (OppWBlkStl*Wins+ OppLBlkStl*Losses)/(Wins+Losses),
           OppAsstRat = (OppWAsstRat*Wins+ OppLAsstRat*Losses)/(Wins+Losses)) %>% 
    select(-Wins, -Losses)
  def_results <-  merge(def_df, opp_def_df, by = c("TeamID", "Season"), all = TRUE) %>%
    select(Season, TeamID, Reb, OReb, ORebRat, BlkStl, TO, TurnRat, AsstRat, 
           OppReb, OppORebRat, OppBlkStl, OppAsstRat)
  #Merge fg and def dataframes
  results <- merge(fg_results, def_results, by = c("TeamID", "Season"), all = TRUE)
  #If first year, create final table, otherwise add data
  ifelse(year == min(CompactResults$Season), DetailedMetrics <- results, 
         DetailedMetrics <- rbind(DetailedMetrics, results))
})
DetailedMetrics_M <- DetailedMetrics
```



```{r}
#Merge All DataFrames
#Merge Metrics
Metrics <- merge(SimpleMetrics_M, DetailedMetrics_M, 
                 by = c("TeamID", "Season", "Games"), all = TRUE)
#Merge metrics and ELO
Predictors <- merge(Metrics, FinalElo_M, by = c("TeamID", "Season"), all.x = TRUE) %>% 
  select(-Games)

```



```{r}
#Save Predictors as CSV
setwd("/Users/jakesak/Documents/MM Mania Kaggle/Data")
write.csv(Predictors, file = "predictors.csv", row.names = FALSE)
```


