---
title: "XGBoost"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr) # for data cleaning
library(xgboost) #For modelling
setwd("/Users/jakesak/Documents/MM Mania Kaggle/Code")
Predictors <- read.csv(file.path("../Data", "predictors.csv" ))
DetailedResults <- read.csv(file.path("../Data", "MRegularSeasonDetailedResults.csv" ))
NCAATourneyCompactResults <- read.csv(file.path("../Data", "MNCAATourneyCompactResults.csv" ))
NCAATourneyCompactResults <- NCAATourneyCompactResults %>% filter(Season >= min(DetailedResults$Season))
NCAATourneySeeds <- read.csv(file.path("../Data", "MNCAATourneySeeds.csv" ))
NCAATourneySeeds <- NCAATourneySeeds %>% filter(Season >= min(DetailedResults$Season))
```

```{r}
#Set up df
results <- NCAATourneyCompactResults
results$Team1 <- ifelse(results$WTeamID < results$LTeamID, results$WTeamID, results$LTeamID)
results$Team2 <- ifelse(results$WTeamID > results$LTeamID, results$WTeamID, results$LTeamID)
results <- results %>% 
  left_join(Predictors, by = c("Team1" = "TeamID", "Season")) %>% 
  rename(T1Win_pct = Win_pct, T1Pts_for = Pts_for, T1Pts_against = Pts_against, 
         T1Pts_diff = Pts_diff, T1LBlowouts = LBlowouts, T1LClose = LClose, 
         T1rawSOS = rawSOS, T1ELOSOS = ELOSOS, T1FgPct = FgPct, T1ThreePtPct = ThreePtPct, 
         T1ThreePtShots = ThreePtShots, T1FtPct = FtPct, T1FtA = FtA,
         T1OppFgPct = OppFgPct, T1OppThreePtPct = OppThreePtPct, 
         T1OppThreePtShots = OppThreePtShots, T1OppFtA = OppFtA, T1Wins = Wins, 
         T1Losses = Losses, T1Reb = Reb, T1OReb = OReb, T1ORebRat = ORebRat, T1Stl = Stl, T1Blk = Blk,
         T1TO = TO, T1TurnRat = TurnRat, T1AsstRat = AsstRat, T1OppOReb = OppOReb, T1OppORebRat = OppORebRat, 
         T1OppBlkStl = OppBlkStl, T1OppAsstRat = OppAsstRat, T1ELO = ELO,
         T1Quad1Rec = Quad1Rec, T1Quad1Games = Quad1Games, T1Rank = Rank)
results<- results %>% 
  left_join(Predictors, by = c("Team2" = "TeamID", "Season")) %>% 
  rename(T2Win_pct = Win_pct, T2Pts_for = Pts_for, T2Pts_against = Pts_against,
         T2Pts_diff = Pts_diff, T2LBlowouts = LBlowouts, T2LClose = LClose, 
         T2rawSOS = rawSOS, T2ELOSOS = ELOSOS, T2FgPct = FgPct, T2ThreePtPct = ThreePtPct, 
         T2ThreePtShots = ThreePtShots, T2FtPct = FtPct, T2FtA = FtA,
         T2OppFgPct = OppFgPct, T2OppThreePtPct = OppThreePtPct, 
         T2OppThreePtShots = OppThreePtShots, T2OppFtA = OppFtA, T2Wins = Wins, 
         T2Losses = Losses, T2Reb = Reb, T2OReb = OReb, T2ORebRat = ORebRat, T2Stl = Stl, T2Blk = Blk,
         T2TO = TO, T2TurnRat = TurnRat, T2AsstRat = AsstRat, T2OppOReb = OppOReb, T2OppORebRat = OppORebRat, 
         T2OppBlkStl = OppBlkStl, T2OppAsstRat = OppAsstRat, T2ELO = ELO,
         T2Quad1Rec = Quad1Rec, T2Quad1Games = Quad1Games, T2Rank = Rank)
results <- results %>%
  left_join(NCAATourneySeeds, by = c("Team1" = "TeamID", "Season")) %>%
  rename(Seed_T1 = Seed)
results <- results %>%
  left_join(NCAATourneySeeds, by = c("Team2" = "TeamID", "Season")) %>%
  rename(Seed_T2 = Seed)
results$SeedNum_T1 <- as.numeric(substr(results$Seed_T1,2,3))
results$SeedNum_T2 <- as.numeric(substr(results$Seed_T2,2,3))
results$Seed_len1 <- substr(results$Seed_T1,1,3)
results$Seed_len2 <- substr(results$Seed_T2,1,3)

results$result <- ifelse(results$WTeamID < results$LTeamID, 1, 0)
results$Score1 <- ifelse(results$WTeamID < results$LTeamID, results$WScore, results$LScore)
results$Score2 <- ifelse(results$WTeamID > results$LTeamID, results$WScore, results$LScore)
results <- results %>%
  mutate(ELO_diff = T1ELO-T2ELO,
        Seed_diff = SeedNum_T1 - SeedNum_T2,
        Win_pct_dif = T1Win_pct - T2Win_pct,
        PTS_for = T1Pts_for - T2Pts_for,
        PTS_against = T1Pts_against - T2Pts_against,
        ThreePtShots_diff = T1ThreePtShots - T2ThreePtShots,
        Reb_diff = T1Reb - T2Reb,
        ORebRate_diff = T1ORebRat - T2ORebRat,
        OppORebRate_diff = T1OppORebRat - T2OppORebRat,
        Turn_diff = T1TO - T2TO,
        rawSOS_diff = T1rawSOS - T2rawSOS,
        ELOSOS_diff = T1ELOSOS - T2ELOSOS,
        Rank_diff = T1Rank - T2Rank,
        Margin_diff = T1Pts_diff - T2Pts_diff)
results <- results[which(results$Seed_len1 != results$Seed_len2),]


#Set Predictors
predictors <- c("T1Win_pct", "T1Pts_for", "T1Pts_against","T1Pts_diff", 
                "T1rawSOS", "T1ELOSOS", "T1FgPct", "T1ThreePtPct", "T1ThreePtShots",
                "T1FtPct", "T1FtA", "T1OppFgPct", "T1OppThreePtPct", "T1OppThreePtShots", 
                "T1OppFtA", "T1Reb", "T1OReb", "T1ORebRat", "T1Stl", "T1Blk",
                "T1TO", "T1TurnRat", "T1AsstRat", "T1OppOReb", "T1OppORebRat", "T1OppBlkStl", 
                "T1ELO", "T1Quad1Rec", "T1Quad1Games", "T2Win_pct", "T2Pts_for", 
                "T2Pts_against", "T2Pts_diff","T2rawSOS", "T2ELOSOS", 
                "T2FgPct", "T2ThreePtPct", "T2ThreePtShots", "T2FtPct", 
                "T2FtA", "T2OppFgPct", "T2OppThreePtPct", "T2OppThreePtShots", 
                "T2OppFtA", "T2Reb", "T2OReb", "T2ORebRat", "T2Stl", "T2Blk",
                "T2TO", "T2TurnRat", "T2AsstRat", "T2OppOReb", "T2OppORebRat","T2OppBlkStl",
                "T2ELO", "T2Quad1Rec", "T2Quad1Games", "ELO_diff", "T1OppAsstRat", "T2OppAsstRat",
                "T1Rank", "T2Rank", "PTS_for", "PTS_against", "Win_pct_dif", 
                "ThreePtShots_diff", "Reb_diff", "ORebRate_diff", "OppORebRate_diff", 
                "Turn_diff","ELOSOS_diff", "Rank_diff", "Margin_diff")
#Unused: "T1LBlowouts", "T2LBlowouts", "T1LClose", "T2LClose", "Seed_diff", "rawSOS_diff", "T1Wins", "T1Losses", "T2Wins", "T2Losses", 



#Set features and label
dtrain <- xgb.DMatrix(data = as.matrix(results[, predictors]), label = results$result)

#Parameters
params <- list(
  eval_metric = "mae",
  #objective = "binary:logistic",
  booster = "gbtree",
  eta = 0.015,
  max_depth = 4,
  subsample = 0.7,
  colsample_bytree = 0.75
)

# Cross-validation
cv_results <- xgb.cv(params = params,
                     data = dtrain,
                     nrounds = 2000,
                     nfold = 5,
                     metrics = "logloss",
                     early_stopping_rounds = 20,
                     maximize = FALSE,
                     Prediction = TRUE,
                     verbose = 0)
# Extract the best number of rounds
best_nrounds <- cv_results$best_iteration
# Re-train the model on the full dataset using the best number of rounds
final_model <- xgb.train(params = params,
                         data = dtrain,
                         nrounds = best_nrounds)
```


```{r}
ErrorTable <- data.frame(Season = numeric(), error = numeric())

for (year in unique(results$Season)) {
  data <- results[which(results$Season == year),]
  dtest <- xgb.DMatrix(data = as.matrix(data[, predictors]))
  predictions <- predict(final_model, dtest)
  true_outcomes <- data$result
  error <- mean((true_outcomes - predictions)^2)
  year_error <- data.frame(Season = year, error = error)
  ErrorTable <- rbind(ErrorTable, year_error)
}

print(ErrorTable)
```

```{r}
#True Acc vs Chalk Acc 2023
data <- results[which(results$Season == 2023),]
true_outcomes <- data$result
dtest <- xgb.DMatrix(data = as.matrix(data[, predictors]))
predictions <- predict(final_model, dtest)
data$pred1 <- ifelse(predictions >= 0.5, 1, 0)
predictions1 <- data$pred1
TrueAcc <-mean(predictions1 == true_outcomes)
print(TrueAcc)

data$Chalk <- ifelse(data$SeedNum_T1 <= data$SeedNum_T2, 
                     1, 0)
predictions2 <- data$Chalk
ChalkAcc <- mean(predictions2 == true_outcomes)
print(ChalkAcc)
```


